// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6514.IRecharge.subsystems;


import org.usfirst.frc6514.IRecharge.Robot;
import org.usfirst.frc6514.IRecharge.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotState;

/**
 *
 */
public class DriveSystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Spark leftDriveSpeedController;
    private Spark rightDriveSpeedController;
    private DifferentialDrive differentialDrive;
    private Encoder leftDriveEncoder;
    private Encoder rightDriveEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    //Robot drive vs  private DifferentialDrive robotDrive;

    enum DriveStyle {
        Tank,
        Arcade
    }

    private DriveStyle UserDriveStyle = DriveStyle.Tank; 



    public DriveSystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        leftDriveSpeedController = new Spark(4);
        addChild("LeftDriveSpeedController",leftDriveSpeedController);
        leftDriveSpeedController.setInverted(false);
        
        rightDriveSpeedController = new Spark(5);
        addChild("RightDriveSpeedController",rightDriveSpeedController);
        rightDriveSpeedController.setInverted(false);
        
        differentialDrive = new DifferentialDrive(leftDriveSpeedController, rightDriveSpeedController);
        addChild("DifferentialDrive",differentialDrive);
        differentialDrive.setSafetyEnabled(true);
        differentialDrive.setExpiration(0.1);
        differentialDrive.setMaxOutput(1.0);

        
        leftDriveEncoder = new Encoder(4, 5, false, EncodingType.k4X);
        addChild("LeftDriveEncoder",leftDriveEncoder);
        leftDriveEncoder.setDistancePerPulse(1.0);
        leftDriveEncoder.setPIDSourceType(PIDSourceType.kRate);
        
        rightDriveEncoder = new Encoder(6, 7, false, EncodingType.k4X);
        addChild("RightDriveEncoder",rightDriveEncoder);
        rightDriveEncoder.setDistancePerPulse(1.0);
        rightDriveEncoder.setPIDSourceType(PIDSourceType.kRate);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

        if (!RobotState.isAutonomous())
        {
            if (UserDriveStyle == DriveStyle.Tank){
                differentialDrive.tankDrive(Robot.oi.joystickDriver.getX(), Robot.oi.joystickDriver.getY());
            }
            else if (UserDriveStyle == DriveStyle.Arcade){ 
                differentialDrive.arcadeDrive(Robot.oi.joystickDriver.getX(), Robot.oi.joystickDriver.getX());
            }
            
        }




    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void toggleDriveStyle() {

        if (UserDriveStyle ==DriveStyle.Tank){
            UserDriveStyle = DriveStyle.Arcade;
        }
        else {
            UserDriveStyle = DriveStyle.Tank;
        }

    }

}

